config/routes.rb
Rails.application.routes.draw do

	root to: 'home#index'
	devise_for :users
	resources :profiles, except: [:index]
	resources :communities do
		resources :posts do
			member do
				get 'like'
				get 'unlike'
			end
			resources :comments, except: [:edit]
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/community.rb
class Community < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: :slugged
	has_many :posts
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :community
  belongs_to :user
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :posts
  has_many :comments
  has_many :communities

  after_create :create_profile

  def create_profile
    Profile.create(user_id:self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :get_community
	before_action :get_post
	before_action :set_post, only: :create
	def index
		@comments = Comment.all
	end

	def show
		@comments = Comment.find(params[:id])
	end


	def new
		@comment = Comment.new(post_id: params[:post_id])
	end


	def create
		if current_user.present?
			@comment = @post.comments.build(comment_params)
			@comment.user = current_user
			if @comment.save
				redirect_to community_post_path(@community, @post), notice: 'Comment was successfully created.'
			else
				render community_post_path(@community, @post), notice: 'Comment was not created.'
			end
		else
			redirect_to new_user_session_path
		end

	end

	private

	def get_community
		@community = Community.friendly.find(params[:community_id])
	end
	def get_post
		@post = Post.friendly.find(params[:post_id])
	end

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_post
		@post = Post.friendly.find params[:post_id]
	end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
	before_action :set_community, only: [:show, :edit, :destroy, :update]

	def index
		@communities = Community.all
	end

	def show
		@community = Community.friendly.find(params[:id])
	end

	def new
		@community = Community.new
	end

	def create
		@community = Community.create(community_params)
		@community.user = current_user
		if @community.save
			redirect_to communities_path, notice: "#{@community.name} was successfully created."
		else
			render :new
		end
	end

	def edit
		@communities = Community.all
	end

	def update
		if @community.update(community_params)
			redirect_to communities_path(@community), notice: "#{@community.name} was successfully updated."
		else
			render :edit
		end
	end

	def destroy
		@community.destroy
		respond_to do |format|
			format.html { redirect_to communities_path(@community), notice: 'Community was successfully destroyed.' }
		end
	end


	private

	def community_params
		params.require(:community).permit(:name, :description)
	end

	def set_community
		@community = Community.friendly.find(params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@communities = Community.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :get_community
	before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
	before_action :authenticate_user!, only: [:edit, :create, :update, :destroy]
	before_action :check_ownership!, only: [:edit, :update, :destroy]

	def index
		@posts = @community.posts
	end

	# GET /posts/1
	# GET /posts/1.json
	def show
	end

	def like
		@post.liked_by current_user
		redirect_to community_post_path(@community, @post)
	end

	def unlike
		@post.unliked_by current_user
		redirect_to community_post_path(@community, @post)
	end

	# GET /posts/new
	def new
		@post = @community.posts.build
		@posts = Post.all
	end

	# GET /posts/1/edit
	def edit
		@posts = Post.all
	end

	# POST /posts
	# POST /posts.json
	def create

		@post = @community.posts.build(post_params)
		@post.user = current_user

		if @post.save
			redirect_to community_post_path(@community, @post), notice: 'Post was successfully created.'
		else
			render :new
		end
	end

	# PATCH/PUT /posts/1
	# PATCH/PUT /posts/1.json
	def update
		if @post.update(post_params)
			redirect_to community_post_path(@community, @post), notice: 'Post was successfully updated.'
		else
			render :edit
		end
	end

	# DELETE /posts/1
	# DELETE /posts/1.json
	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to community_posts_url(@community), notice: 'Post was successfully destroyed.' }
		end
	end

	private

	def get_community
		@community = Community.friendly.find(params[:community_id])
	end

	# Use callbacks to share common setup or constraints between actions.
	def set_post
		@post = Post.friendly.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def post_params
		params.require(:post).permit(:title, :content)
	end

	def check_ownership!
		unless @post.user === current_user
			flash[:alert] = "This ain't your post buddy!"
			redirect_back fallback_location: root_path
		end
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:show, :edit, :update, :destroy]
	before_action :check_owner

	# GET /profiles
	# GET /profiles.json
	def index
		@profiles = Profile.all
	end

	# GET /profiles/1
	# GET /profiles/1.json
	def show
	end

	# GET /profiles/new
	def new
		@profile = Profile.new
	end

	# GET /profiles/1/edit
	def edit
	end

	# POST /profiles
	# POST /profiles.json
	def create
		@profile = Profile.new(profile_params)

		respond_to do |format|
			if @profile.save
				format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
				format.json { render :show, status: :created, location: @profile }
			else
				format.html { render :new }
				format.json { render json: @profile.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /profiles/1
	# PATCH/PUT /profiles/1.json
	def update
		respond_to do |format|
			if @profile.update(profile_params)
				format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
				format.json { render :show, status: :ok, location: @profile }
			else
				format.html { render :edit }
				format.json { render json: @profile.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /profiles/1
	# DELETE /profiles/1.json
	def destroy
		@profile.destroy
		respond_to do |format|
			format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_profile
		@profile = Profile.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def profile_params
		params.require(:profile).permit(:user_id, :first_name, :last_name, :nick_name, :bio, :picture)
	end

	def check_owner
		unless @profile.user === current_user
			redirect_to root_path, notice: 'uh uh'
		end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comment/index.html.erb
<p id="notice"><%= notice %></p>
<% @post.comment.each do |comment| %>
	<tr>
		<td><%= comment.name %></td>
		<td><%= comment.content %></td>
	</tr>
<% end %>

app/views/comment/new.html.erb
<h3>New</h3>
<%= form_with model:@comment, local:true do |form| %>
	<div class="form-group">
		<%= form.label :name %>
		<%= form.text_field :name, class:'form-control' %>
	</div>
	
	<div class="form-group">
		<%= form.label :message %>
		<%= form.text_field :content, class:'form-control' %>
	</div>
	
	<div class="actions">
		<%= form.submit 'Create', class:'btn btn-success' %>
	</div>
<% end %>

app/views/comment/show.html.erb
<% @post.comment.each do |comment| %>
	<tr>
		<td><%= comment.name %></td>
		<td><%= comment.content %></td>
	</tr>
<% end %>

app/views/communities/_form.html.erb
<h3>New</h3>
<%= form_with(model: [@community], local:true) do |form| %>
	<div class="form-group">
		<%= form.label :name %>
		<%= form.text_field :name, class:'form-control' %>
	</div>
	
	<div class="form-group">
		<%= form.label :description %>
		<%= form.text_field :description, class:'form-control' %>
	</div>
	
	<div class="actions">
		<%= form.submit 'Create', class:'btn btn-success' %>
	</div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Show', community_posts_path(@community) %> |
<%= link_to 'Back', community_posts_path(@community) %>

app/views/communities/index.html.erb
<h1>Communities</h1>

<% if user_signed_in? %>
	<%= link_to "New", new_community_path, class: "btn btn-success mt-3" %>
<% end %>

<div class="text-center">
	<div class="row">
		<% @communities.each do |community| %>
			<div class="col-sm-4">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title"><%= community.name %></h5>
						<%= link_to "Enter", community_posts_path(community), class: "btn btn-success mt-3" %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/communities/new.html.erb
<%= render 'form', community: @community %>

<%= link_to 'Back', communities_path %>

app/views/home/index.html.erb
<%#= link_to 'profile', profile_path(current_user.profile) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RedditWebsite</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<script
		src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
		crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
	
	<%= link_to root_path, class: 'navbar-brand' do %>
		<i class="fab fa-reddit"></i> reddit
	<% end %>
	
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<%= link_to 'Communities', communities_path, class: 'nav-link' %>
			</li>
		</ul>
		
		<span class="navbar-text">
			<% if user_signed_in? %>
		<%= current_user.email %> <%= current_user.votes.count %>
				<li>
			<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
		</li>
	<% else %>
		<li>
			<%= link_to('Login', new_user_session_path) %>
		</li>
	<% end %>
		</span>
		
<!--		<div class="dropdown">-->
<!--			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
				<%# if user_signed_in? %>
					<%#  %>
				<%# else %>
					<%#= link_to 'profile', profile_path(current_user.profile), class:"dropdown-item" %>
				<%# end %>
<!--			</button>-->
<!--			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">-->
				<%#= link_to 'profile', profile_path(current_user.profile), class:"dropdown-item" %>
<!--			</div>-->
<!--		</div>-->
	</div>
</nav>
<div class="container">
	
	<%= yield %>
	
	<% if notice || alert %>
		<% if notice %>
			<div class="alert alert-success">
				<%= notice %>
			</div>
		<% else %>
			<div class="alert alert-danger">
				<%= alert %>
			</div>
		<% end %>
	<% end %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%#= tinymce_assets %>
<%= form_with(model: [@community, post], local: true) do |form| %>
	<% if post.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
			
			<ul>
				<% post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= form.label :title %>
		<%= form.text_field :title, class: 'form-control' %>
	</div>
	
	<div class="form-group">
		<%= form.label :content %>
		<%= form.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
	</div>
	
	<div class="actions">
		<%= form.submit 'Create', class: 'btn btn-success' %>
	</div>
<% end %>
<script type="text/javascript" charset="utf-8">
	$(document).on('turbolinks:load', function(){
		tinymce.init({
			selector: "textarea.tinymce",
			toolbar: 'styleselect | bold italic | undo redo | alignleft aligncenter alignright alignjustify alignnone | pagebreak code | link quickimage media | insertfile | help',
			menubar: 'insert',
			plugins: ['image link quickbars table media help code pagebreak'],
			relative_urls: false,
			skin: "oxide",
			link_list: [
				<% @posts.each do |post| %>
				{title: '<%= post.title %>', value: '<%= community_post_path(@community, post) %>'},
				<% end %>
			]
		})
	});
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', community_post_path(@community, @post) %> |
<%= link_to 'Back', community_posts_path(@community) %>

app/views/posts/index.html.erb
<h1><%= @community.name %></h1>

<% if @community.user === current_user %>
	<%= link_to 'Edit', edit_community_path(@community), class: "btn btn-sm btn-outline-info" %>
	<%= link_to "Delete", community_path(@community), class: "btn btn-sm btn-outline-danger",
	            method: :delete,
	            data: {confirm: "You sure?"}%>
<% end %>
<%= link_to 'Back', communities_path(@community), class: "btn btn-primary" %>

<table class="table">
	<thead>
	<tr>
		<th>Topic</th>
		<th>Comments</th>
		<th>Author</th>
		<th>Created</th>
	</tr>
	</thead>
	
	<tbody>
	<% @posts.each do |post| %>
		<tr>
			<td><%= link_to post.title, community_post_path(@community, post) %></td>
			<td><%= post.comments.count %></td>
			<td><%= post.user_id %></td>
			<td><%= time_ago_in_words(post.created_at) %></td>
		</tr>
	<% end %>
	</tbody>
</table>
<% if user_signed_in? %>
<%= link_to "New", new_community_post_path, class:"btn btn-success mt-3" %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', community_posts_path %>

app/views/posts/show.html.erb
<div>
	<h1><%= @post.title %></h1>
	<p><%= raw @post.content %></p>
</div>

<% if user_signed_in? %>
	<% if current_user.voted_for? @post %>
		<%= link_to unlike_community_post_path(@community, @post) do %>
			<i class="fas fa-thumbs-up"></i>
		<% end %>
	<% else %>
		<%= link_to like_community_post_path(@community, @post) do %>
			<i class="far fa-thumbs-up"></i>
		<% end %>
	<% end %>
<% else %>
	<i class="far fa-thumbs-up"></i>
<% end %>

<%= @post.votes_for.size %>

<table class="table">
	<thead>
	<tr>
		<th>User Name</th>
		<th>Comments</th>
		<th>Created</th>
	</tr>
	</thead>
	
	<tbody>
	<% @post.comments.each do |comment| %>
		<tr>
			<td><%= comment.user.profile.nick_name %></td>
			<td><%= comment.content %></td>
			<td><%= time_ago_in_words(comment.created_at) %></td>
		</tr>
	<% end %>
	</tbody>
</table>


<% if user_signed_in? %>
	<%= form_with model: [@community, @post, @post.comments.build], local: true do |comment| %>
		<div class="input-group">
			<div class="input-group-prepend">
				<%= comment.label :comment, class: "input-group-text" %>
			</div>
			<%= comment.text_area :content, class: "form-control" %>
		</div>
		
		<div class="actions">
			<%= comment.submit 'Create Comment', class: 'btn btn-success' %>
		</div>
	<% end %>
<% end %>


<% if current_user === @post.user || current_user.try(:admin?) %>
	<%= link_to 'Edit', edit_community_post_path(@community, @post), class: "btn btn-primary" %>
	<%= link_to "Delete", community_post_path(@post.community, @post), class: "btn btn-primary",
	            method: :delete,
	            data: {confirm: "You sure?"} %>
<% end %>
<%= link_to 'Back', community_posts_path(@community), class: "btn btn-primary" %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :nick_name %>
    <%= form.text_field :nick_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Nick name</th>
      <th>Bio</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.nick_name %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.picture %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Nick name:</strong>
  <%= @profile.nick_name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @profile.picture %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>